---
- include: aws-codedeploy.yml
  vars:
    nginx_conf_template: templates/index.html.j2
    nginx_conf_file_path: /usr/share/nginx/www/index.html
    nginx_index_template: templates/index.html.j2
    nginx_index_file_path: /usr/share/nginx/www/index.html
    nginx_ppa_version: stable
    nginx_ppa_use: false

  handlers:
    - name : reload nginx
      servive: name=nginx state=reloaded
  
  tasks:
    - name: Add PPA for Nginx.
      apt_repository:
        repo: 'ppa:nginx/{{ nginx_ppa_version }}'
        state: present
        update_cache: yes
      register: nginx_ppa_added
      when: nginx_ppa_use

    - name: Ensure nginx will reinstall if the PPA was just added.
      apt:
        name: nginx
        state: absent
      when: nginx_ppa_added.changed
      
    - name updating cache
      apt: update_cache=yes cache_valid_time=86400
      changed_when: false
      
    - name : install nginx
      apt: 
        name: nginx 
        state: installed
        default_release: stable
      
    - name: Copy index file.
      template:
        src: "{{ nginx_index_template }}"
        dest: "{{ nginx_index_file_path }}"
        owner: root
        group: root
        mode: 0644

    - name: Copy conf file.
      template:
         src: "{{ nginx_conf_template }}"
         dest: "{{ nginx_conf_file_path }}"
         owner: root
         group: root
         mode: 0644
      notify:     
          - reload nginx

    - name: Ensure nginx is started and enabled to start at boot.
      service: name=nginx state=started enabled=yes
