---
- include: aws-codedeploy.yml

- name: including vars file
  include_vars: variables.yml

- name: Add PPA for Nginx.
  apt_repository:
    repo: 'ppa:nginx/{{ nginx_ppa_version }}'
    state: present
    update_cache: yes
  register: nginx_ppa_added
  when: nginx_ppa_use
- name: Ensure nginx will reinstall if the PPA was just added.
  apt:
    name: nginx
    state: absent
    when: nginx_ppa_added.changed
    
- name updating cache
  apt: update_cache=yes cache_valid_time=86400
  changed_when: false
      
- name : install nginx
  apt: 
    name: nginx 
    state: installed
    default_release: stable
      
- name: Copy index file.
  template:
    src: "{{ nginx_index_template }}"
    dest: "{{ nginx_index_file_path }}"
    owner: root
    group: root
    mode: 0644

- name: Copy conf file.
  template:
     src: "{{ nginx_conf_template }}"
     dest: "{{ nginx_conf_file_path }}"
     owner: root
     group: root
     mode: 0644
  notify:     
      - reload nginx

- name: Ensure nginx is started and enabled to start at boot.
  service: name=nginx state=started enabled=yes
